name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request_target:  # to allow testing from forks
    branches: [ "main" ]
  workflow_call:  # for triggering from pypi-release.yml
    secrets:
      LLM_API_KEY:
        required: false # or true if you always need it

permissions:
  contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
        echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
    - name: Test with pytest
      if: matrix.python-version != '3.13'
      env:
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        LLM_API_TYPE: openai
        MODEL: "gpt-5.2"
      run: |
        pytest
    - name: Test with pytest +coverage
      if: matrix.python-version == '3.13'
      env:
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        LLM_API_TYPE: openai
        MODEL: "gpt-5.2"
      run: |
        pytest --cov=gito --cov-report=xml
    - name: Generate coverage badge
      if: |
        matrix.python-version == '3.13' && (
          github.event_name == 'push' ||
          (github.event_name == 'pull_request_target'
            && github.event.pull_request.head.repo.full_name == github.repository
          )
        )
      run: |
        pip install genbadge[coverage]
        genbadge coverage -i coverage.xml -o coverage.svg
    - name: Commit coverage badge
      if: |
        matrix.python-version == '3.13' && (
          github.event_name == 'push' ||
          (github.event_name == 'pull_request_target'
            && github.event.pull_request.head.repo.full_name == github.repository
          )
        )
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch origin
        git checkout ${{ github.head_ref || github.ref_name }} --
        git add coverage.svg
        git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
